import type { AppData } from "@/lib/types";

const organizationId = "demo-org";

export const demoData: AppData = {
  profile: {
    id: "profile-ben",
    organization_id: organizationId,
    full_name: "Demo Administrator",
    email: "admin@example.invalid",
    role: "admin",
    active: true,
  },
  profiles: [
    {
      id: "profile-ben",
      organization_id: organizationId,
      full_name: "Demo Administrator",
      email: "admin@example.invalid",
      role: "admin",
      active: true,
    },
    {
      id: "profile-maya",
      organization_id: organizationId,
      full_name: "Demo Manager",
      email: "manager@example.invalid",
      role: "manager",
      active: true,
    },
    {
      id: "profile-liam",
      organization_id: organizationId,
      full_name: "Demo Electrician",
      email: "electrician@example.invalid",
      role: "employee",
      active: true,
    },
    {
      id: "profile-noah",
      organization_id: organizationId,
      full_name: "Demo Apprentice",
      email: "apprentice@example.invalid",
      role: "employee",
      active: true,
    },
  ],
  clients: [
    {
      id: "client-1",
      organization_id: organizationId,
      company_name: "Example Farm Ltd.",
      contact_name: "Sample Contact",
      email: "contact1@example.invalid",
      city: "Sampletown",
      status: "active",
      source: "Referral",
      created_at: "2026-07-08T14:00:00.000Z",
    },
    {
      id: "client-2",
      organization_id: organizationId,
      company_name: "Example Community Centre",
      contact_name: "Demo Contact",
      email: "contact2@example.invalid",
      city: "Demo City",
      status: "active",
      source: "Website",
      created_at: "2026-07-12T14:00:00.000Z",
    },
    {
      id: "client-3",
      organization_id: organizationId,
      company_name: "Sample Manufacturing",
      contact_name: "Example Lead",
      email: "contact3@example.invalid",
      city: "Exampleville",
      status: "lead",
      source: "Existing customer",
      created_at: "2026-07-19T14:00:00.000Z",
    },
  ],
  jobs: [
    {
      id: "job-1",
      organization_id: organizationId,
      client_id: "client-1",
      job_number: "SC-26071",
      title: "Grain dryer service upgrade",
      service_type: "Commercial",
      status: "in_progress",
      priority: "high",
      city: "Sampletown",
      scheduled_start: "2026-07-23T13:00:00.000Z",
      scheduled_end: "2026-07-25T22:00:00.000Z",
      budget_hours: 42,
      created_at: "2026-07-08T14:00:00.000Z",
    },
    {
      id: "job-2",
      organization_id: organizationId,
      client_id: "client-2",
      job_number: "SC-26074",
      title: "Gym LED retrofit",
      service_type: "LED Lighting",
      status: "scheduled",
      priority: "normal",
      city: "Demo City",
      scheduled_start: "2026-07-24T13:00:00.000Z",
      scheduled_end: "2026-07-24T22:00:00.000Z",
      budget_hours: 24,
      created_at: "2026-07-12T14:00:00.000Z",
    },
    {
      id: "job-3",
      organization_id: organizationId,
      client_id: "client-3",
      job_number: "SC-26078",
      title: "Shop solar assessment",
      service_type: "Solar",
      status: "quoted",
      priority: "normal",
      city: "Exampleville",
      budget_hours: 36,
      created_at: "2026-07-19T14:00:00.000Z",
    },
  ],
  timeEntries: [
    {
      id: "time-1",
      organization_id: organizationId,
      employee_id: "profile-liam",
      job_id: "job-1",
      start_time: "2026-07-22T13:04:00.000Z",
      end_time: "2026-07-22T21:32:00.000Z",
      break_minutes: 30,
      status: "approved",
    },
    {
      id: "time-2",
      organization_id: organizationId,
      employee_id: "profile-noah",
      job_id: "job-1",
      start_time: "2026-07-22T13:10:00.000Z",
      end_time: "2026-07-22T22:02:00.000Z",
      break_minutes: 30,
      status: "submitted",
      notes: "Completed service entrance rough-in.",
    },
  ],
};
