import type { Client, Employee, Job, TimeEntry } from './types'

// All records in this file are fictional product-demo data.
export const employees: Employee[] = [
  {
    id: 'emp-1',
    name: 'Demo Administrator',
    role: 'admin',
    title: 'Owner / Master Electrician',
    email: 'admin@example.invalid',
    phone: '(204) 555-0101',
    hourlyRate: 95,
    initials: 'DA',
  },
  {
    id: 'emp-2',
    name: 'Demo Journeyperson',
    role: 'employee',
    title: 'Journeyman Electrician',
    email: 'journeyperson@example.invalid',
    phone: '(204) 555-0102',
    hourlyRate: 52,
    initials: 'DJ',
  },
  {
    id: 'emp-3',
    name: 'Demo Electrician',
    role: 'employee',
    title: 'Journeyman Electrician',
    email: 'electrician@example.invalid',
    phone: '(204) 555-0103',
    hourlyRate: 48,
    initials: 'DE',
  },
  {
    id: 'emp-4',
    name: 'Demo Apprentice',
    role: 'employee',
    title: 'Apprentice / Boring Operator',
    email: 'apprentice@example.invalid',
    phone: '(204) 555-0104',
    hourlyRate: 34,
    initials: 'DA',
  },
  {
    id: 'emp-5',
    name: 'Demo Solar Technician',
    role: 'employee',
    title: 'Solar Technician',
    email: 'solar@example.invalid',
    phone: '(204) 555-0105',
    hourlyRate: 44,
    initials: 'DS',
  },
]

export const clients: Client[] = [
  {
    id: 'cl-1',
    name: 'Example Farm Ltd.',
    contact: 'Sample Contact',
    type: 'agricultural',
    email: 'farm@example.invalid',
    phone: '(204) 555-0201',
    address: '100 Demo Road',
    city: 'Sampletown, MB',
    notes: 'Grain operation. New shop wiring + grain dryer 200A service.',
    createdAt: '2026-05-02',
  },
  {
    id: 'cl-2',
    name: 'Example Grocery Co-op',
    contact: 'Demo Contact',
    type: 'commercial',
    email: 'facilities@example.invalid',
    phone: '(204) 555-0202',
    address: '200 Sample Avenue',
    city: 'Demo City, MB',
    notes: 'Refrigeration panel upgrade. After-hours access required.',
    createdAt: '2026-05-19',
  },
  {
    id: 'cl-3',
    name: 'Sample Residence',
    contact: 'Example Homeowner',
    type: 'residential',
    email: 'homeowner@example.invalid',
    phone: '(204) 555-0203',
    address: '300 Example Street',
    city: 'Exampleville, MB',
    notes: 'Rooftop solar + battery backup. South-facing garage roof.',
    createdAt: '2026-06-01',
  },
  {
    id: 'cl-4',
    name: 'Example Feed & Supply',
    contact: 'Sample Manager',
    type: 'commercial',
    email: 'manager@example.invalid',
    phone: '(204) 555-0204',
    address: '400 Test Drive',
    city: 'Sample City, MB',
    notes: 'Warehouse LED retrofit, 3-phase.',
    createdAt: '2026-06-11',
  },
  {
    id: 'cl-5',
    name: 'Demo Residence',
    contact: 'Demo Homeowner',
    type: 'residential',
    email: 'residential@example.invalid',
    phone: '(204) 555-0205',
    address: '500 Placeholder Crescent',
    city: 'Demo Town, MB',
    notes: 'Basement development, hot tub subpanel.',
    createdAt: '2026-06-24',
  },
  {
    id: 'cl-6',
    name: 'Sample Ag Services',
    contact: 'Example Coordinator',
    type: 'agricultural',
    email: 'ag@example.invalid',
    phone: '(204) 555-0206',
    address: '600 Demonstration Highway',
    city: 'Example Junction, MB',
    notes: 'Directional boring for underground service to new bins.',
    createdAt: '2026-07-03',
  },
]

// Reference week: Mon Jul 20 – Sun Jul 26, 2026
export const jobs: Job[] = [
  {
    id: 'job-1',
    code: 'SC-1042',
    title: 'Shop wiring + 200A grain dryer service',
    clientId: 'cl-1',
    status: 'in-progress',
    category: 'electrical',
    address: '100 Demo Road',
    city: 'Sampletown, MB',
    assignedTo: ['emp-2', 'emp-4'],
    scheduledDate: '2026-07-20',
    estimatedHours: 64,
    description:
      'Run new 200A service to grain dryer, wire machine shop with 12 circuits, install sub-panel.',
    createdAt: '2026-05-04',
  },
  {
    id: 'job-2',
    code: 'SC-1051',
    title: 'Refrigeration panel upgrade',
    clientId: 'cl-2',
    status: 'scheduled',
    category: 'electrical',
    address: '200 Sample Avenue',
    city: 'Demo City, MB',
    assignedTo: ['emp-3'],
    scheduledDate: '2026-07-23',
    estimatedHours: 16,
    description: 'Replace aging refrigeration distribution panel. After-hours work.',
    createdAt: '2026-05-20',
  },
  {
    id: 'job-3',
    code: 'SC-1055',
    title: '8.4kW rooftop solar + battery backup',
    clientId: 'cl-3',
    status: 'in-progress',
    category: 'solar',
    address: '300 Example Street',
    city: 'Exampleville, MB',
    assignedTo: ['emp-5', 'emp-3'],
    scheduledDate: '2026-07-21',
    estimatedHours: 40,
    description:
      '24-panel array on garage roof, hybrid inverter, 10kWh battery, net-metering paperwork.',
    createdAt: '2026-06-02',
  },
  {
    id: 'job-4',
    code: 'SC-1060',
    title: 'Warehouse LED retrofit (3-phase)',
    clientId: 'cl-4',
    status: 'scheduled',
    category: 'electrical',
    address: '400 Test Drive',
    city: 'Sample City, MB',
    assignedTo: ['emp-2', 'emp-4'],
    scheduledDate: '2026-07-24',
    estimatedHours: 24,
    description: 'Retrofit 60 high-bay fixtures to LED, add occupancy sensors.',
    createdAt: '2026-06-12',
  },
  {
    id: 'job-5',
    code: 'SC-1063',
    title: 'Basement development + hot tub subpanel',
    clientId: 'cl-5',
    status: 'completed',
    category: 'electrical',
    address: '500 Placeholder Crescent',
    city: 'Demo Town, MB',
    assignedTo: ['emp-3'],
    scheduledDate: '2026-07-17',
    estimatedHours: 20,
    description: 'Rough-in and finish basement, 60A hot tub subpanel and GFCI.',
    createdAt: '2026-06-25',
  },
  {
    id: 'job-6',
    code: 'SC-1067',
    title: 'Directional bore — underground service to bins',
    clientId: 'cl-6',
    status: 'scheduled',
    category: 'boring',
    address: '600 Demonstration Highway',
    city: 'Example Junction, MB',
    assignedTo: ['emp-4', 'emp-2'],
    scheduledDate: '2026-07-25',
    estimatedHours: 18,
    description: 'Bore 220m under yard and approach for 3-phase underground feed to grain bins.',
    createdAt: '2026-07-04',
  },
  {
    id: 'job-7',
    code: 'SC-1070',
    title: 'Panel inspection & quote',
    clientId: 'cl-5',
    status: 'lead',
    category: 'electrical',
    address: '500 Placeholder Crescent',
    city: 'Demo Town, MB',
    assignedTo: [],
    scheduledDate: '2026-07-27',
    estimatedHours: 2,
    description: 'Homeowner requesting quote for detached garage feed.',
    createdAt: '2026-07-19',
  },
]

function iso(date: string, h: number, m = 0) {
  return new Date(`${date}T${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:00`).toISOString()
}

export const timeEntries: TimeEntry[] = [
  // Fictional sample entries for UI and reporting previews.
  { id: 'te-1', employeeId: 'emp-2', jobId: 'job-1', date: '2026-07-20', clockIn: iso('2026-07-20', 7, 30), clockOut: iso('2026-07-20', 16, 30), breakMinutes: 30, notes: 'Ran feeders to dryer.', manual: false },
  { id: 'te-2', employeeId: 'emp-4', jobId: 'job-1', date: '2026-07-20', clockIn: iso('2026-07-20', 7, 30), clockOut: iso('2026-07-20', 16, 0), breakMinutes: 30, notes: 'Trenching + conduit.', manual: false },
  { id: 'te-3', employeeId: 'emp-2', jobId: 'job-1', date: '2026-07-21', clockIn: iso('2026-07-21', 7, 45), clockOut: iso('2026-07-21', 17, 0), breakMinutes: 45, notes: '', manual: false },
  { id: 'te-4', employeeId: 'emp-4', jobId: 'job-1', date: '2026-07-22', clockIn: iso('2026-07-22', 8, 0), clockOut: iso('2026-07-22', 16, 30), breakMinutes: 30, notes: 'Sub-panel set.', manual: true },
  { id: 'te-5', employeeId: 'emp-5', jobId: 'job-3', date: '2026-07-21', clockIn: iso('2026-07-21', 8, 0), clockOut: iso('2026-07-21', 16, 45), breakMinutes: 30, notes: 'Racking + 12 panels.', manual: false },
  { id: 'te-6', employeeId: 'emp-3', jobId: 'job-3', date: '2026-07-21', clockIn: iso('2026-07-21', 8, 0), clockOut: iso('2026-07-21', 16, 45), breakMinutes: 30, notes: '', manual: false },
  { id: 'te-7', employeeId: 'emp-5', jobId: 'job-3', date: '2026-07-22', clockIn: iso('2026-07-22', 7, 45), clockOut: iso('2026-07-22', 15, 30), breakMinutes: 30, notes: 'Inverter mount + wiring.', manual: false },
  { id: 'te-8', employeeId: 'emp-3', jobId: 'job-5', date: '2026-07-17', clockIn: iso('2026-07-17', 8, 30), clockOut: iso('2026-07-17', 17, 0), breakMinutes: 45, notes: 'Finish + inspection.', manual: false },
]
